/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: zixisun02 (https://sketchfab.com/dogerlo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dinosaur-3e12af7c5c354ea6b01bccfb529a9c02
title: Dinosaur
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Dino/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} rotation={[0, -45, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Dino_Dino_0.geometry}
              material={materials.Dino}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Dino/scene.gltf')
